wip, p30actl

diff --git a/scripts/p30actl b/scripts/p30actl
--- a/scripts/p30actl
+++ b/scripts/p30actl
@@ -80,58 +80,48 @@ RELEASE_HOME="${P30A_HOME}/release"
 RELEASE_HEAD="${RELEASE_HOME}/head"
 PID=`getPid`
 
-## test start
-if [ "${CMD}" = "statustest" ]; then
-  status
-else
-  exit 1
-fi
-
-##
-
 ## under construction
 #if [ "${CMD}" = "restart" ]; then
 #  . $0 stop && . $0 start ${ENV}
 #  exit $?
 #fi
-#if [ "${CMD}" = "start" ]; then
-#  if [ ! -d "${RELEASE_HEAD}" ]; then
-#    echo "[ERROR]"
-#    echo "  - '${RELEASE_HEAD}' does not exist."
-#    exit 1
-#  fi
-#  echo "=== p30-ktor start. env: ${ENV} ===" | tee -a ${LOG}
-#  echo `date` | tee -a ${LOG}
-#  RELEASE_HEAD_LINK=`(cd ${RELEASE_HEAD}; pwd)`
-#  RELEASE_HEAD_REAL=`dirname ${RELEASE_HEAD_LINK}`/`readlink ${RELEASE_HEAD_LINK}`
-#  COUNT=`echo ${RELEASE_HOME}/ | wc -c | sed -e 's/ //g'`
-#  echo "Build No: "`echo ${RELEASE_HEAD_REAL} | cut -c${COUNT}-` | tee -a ${LOG}
-#  cd ${RELEASE_HEAD_LINK}/${APPNAME}*
-#
-#  ## Start p30-ktor Server
+if [ "${CMD}" = "start" ]; then
+  if [ ! -d "${RELEASE_HEAD}" ]; then
+    echo "[ERROR]"
+    echo "  - '${RELEASE_HEAD}' does not exist."
+    exit 1
+  fi
+  echo "=== p30-ktor start. env: ${ENV} ===" | tee -a ${LOG}
+  echo `date` | tee -a ${LOG}
+  RELEASE_HEAD_LINK=`(cd ${RELEASE_HEAD}; pwd)`
+  RELEASE_HEAD_REAL=`dirname ${RELEASE_HEAD_LINK}`/`readlink ${RELEASE_HEAD_LINK}`
+  COUNT=`echo ${RELEASE_HOME}/ | wc -c | sed -e 's/ //g'`
+  echo "Build No: "`echo ${RELEASE_HEAD_REAL} | cut -c${COUNT}-` | tee -a ${LOG}
+  cd ${RELEASE_HEAD_LINK}/bin
+
+  ## Start p30-ktor Server
 #  #OPTS="-Dconfig.file=conf/_${ENV}/env.conf -Dlogger.file=conf/_${ENV}/logger.xml -J-Xmx1G -J-Xms512M"
 #  #nohup ./bin/${APPNAME} ${OPTS} 1>> ${LOG} 2>&1 &
-#  sleep 1
-#  PID=`getPid`
-#  status true; CODE=$?
-#  while [ "$CODE" -ne 0 ]; do
-#    sleep 1
-#    PID=`getPid`
-#    status true; CODE=$?
-#  done
-#elif [ "${CMD}" = "stop" ]; then
-#  if [ ! -n "${PID}" ]; then
-#    echo "$APPNAME is NOT running."
-#    exit 1
-#  fi
-#  kill -15 ${PID}
-#  echo `date` | tee -a ${LOG}
-#  echo "=== $APPNAME stop. pid: ${PID} ===" | tee -a ${LOG}
-#  echo "" | tee -a ${LOG}
-#elif [ "${CMD}" = "status" ]; then
-#  status
-#else
-#  usage
-#fi
-#
-
+  nohup ./com.dignicate.p30a-ktor 1>> ${LOG} 2>&1 &
+  sleep 1
+  PID=`getPid`
+  status true; CODE=$?
+  while [ "$CODE" -ne 0 ]; do
+    sleep 1
+    PID=`getPid`
+   status true; CODE=$?
+  done
+elif [ "${CMD}" = "stop" ]; then
+  if [ ! -n "${PID}" ]; then
+    echo "$APPNAME is NOT running."
+    exit 1
+  fi
+  kill -15 ${PID}
+  echo `date` | tee -a ${LOG}
+  echo "=== $APPNAME stop. pid: ${PID} ===" | tee -a ${LOG}
+  echo "" | tee -a ${LOG}
+elif [ "${CMD}" = "status" ]; then
+  status
+else
+  usage
+fi
